fix: Disable workflow actions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,69 +40,68 @@ jobs:
         uses: gradle/gradle-build-action@v2
         with:
           arguments: build test publish
-        env:
-          SNAPSHOTS_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
-          SNAPSHOTS_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@v3
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/test/TEST-*.xml'
-      - name: Query Version
-        run: |
-          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"
-        id: fetch-version
-      - name: Get Version
-        run: |
-          echo "version_name=${{steps.fetch-version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
-      - name: Upload to Modrinth & Hangar
-        uses: WiIIiam278/mc-publish@hangar
-        with:
-          modrinth-id: SSXTD3me
-          modrinth-featured: false
-          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
-          hangar-id: William278/HuskChat
-          hangar-token: ${{ secrets.HANGAR_API_KEY }}
-          files-primary: target/HuskChat-Plugin-*.jar
-          name: HuskChat v${{ env.version_name }}
-          version: ${{ env.version_name }}
-          changelog: ${{ github.event.head_commit.message }}
-          hangar-version-type: Alpha
-          modrinth-version-type: alpha
-          game-versions: |
-            1.16
-            1.16.1
-            1.16.2
-            1.16.3
-            1.16.4
-            1.16.5
-            1.17
-            1.17.1
-            1.18
-            1.18.1
-            1.18.2
-            1.19
-            1.19.1
-            1.19.2
-            1.19.3
-            1.19.4
-            1.20
-            1.20.1
-            1.20.2
-          modrinth-dependencies: |
-            unsignedvelocity | suggests | *
-            signedvelocity | suggests | *
-            papiproxybridge | suggests | *
-            placeholderapi | suggests | *
-          loaders: |
-            bungeecord
-            velocity
-            spigot
-            paper
-            folia
-          java: 16
+#        env:
+#          SNAPSHOTS_MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
+#          SNAPSHOTS_MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
+#      - name: Publish Test Report
+#        uses: mikepenz/action-junit-report@v3
+#        if: success() || failure() # always run even if the previous step fails
+#        with:
+#          report_paths: '**/build/test-results/test/TEST-*.xml'
+#      - name: Query Version
+#        run: |
+#          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew properties --no-daemon --console=plain -q | grep "^version:" | awk '{printf $2}')"
+#        id: fetch-version
+#      - name: Get Version
+#        run: |
+#          echo "version_name=${{steps.fetch-version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
+#      - name: Upload to Modrinth & Hangar
+#        uses: WiIIiam278/mc-publish@hangar
+#        with:
+#          modrinth-id: SSXTD3me
+#          modrinth-featured: false
+#          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
+#          hangar-id: William278/HuskChat
+#          hangar-token: ${{ secrets.HANGAR_API_KEY }}
+#          files-primary: target/HuskChat-Plugin-*.jar
+#          name: HuskChat v${{ env.version_name }}
+#          version: ${{ env.version_name }}
+#          changelog: ${{ github.event.head_commit.message }}
+#          hangar-version-type: Alpha
+#          modrinth-version-type: alpha
+#          game-versions: |
+#            1.16
+#            1.16.1
+#            1.16.2
+#            1.16.3
+#            1.16.4
+#            1.16.5
+#            1.17
+#            1.17.1
+#            1.18
+#            1.18.1
+#            1.18.2
+#            1.19
+#            1.19.1
+#            1.19.2
+#            1.19.3
+#            1.19.4
+#            1.20
+#            1.20.1
+#            1.20.2
+#          modrinth-dependencies: |
+#            unsignedvelocity | suggests | *
+#            signedvelocity | suggests | *
+#            papiproxybridge | suggests | *
+#            placeholderapi | suggests | *
+#          loaders: |
+#            bungeecord
+#            velocity
+#            spigot
+#            paper
+#            folia
+#          java: 16
       - name: Upload GitHub Artifact
-        if: success() || failure()
         uses: actions/upload-artifact@v2
         with:
           name: HuskChat Plugin
